// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/create": {
    params: {};
  };
  "/join": {
    params: {};
  };
  "/p/:roomId": {
    params: {
      "roomId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/create" | "/join" | "/p/:roomId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/create.tsx": {
    id: "routes/create";
    page: "/create";
  };
  "routes/join.tsx": {
    id: "routes/join";
    page: "/join";
  };
  "routes/play.tsx": {
    id: "routes/play";
    page: "/p/:roomId";
  };
};